/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EncryptedEvent {
  'id' : EventId,
  'startTime' : Timestamp,
  'endTime' : Timestamp,
  'encryptedTitle' : string,
  'encryptedDescription' : string,
}
export interface EncryptedTask {
  'id' : TaskId,
  'isCompleted' : boolean,
  'deadline' : [] | [Timestamp],
  'encryptedDetails' : string,
  'encryptedTitle' : string,
}
export type EventId = bigint;
export type TaskId = bigint;
export type Timestamp = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEvent' : ActorMethod<[Timestamp, Timestamp, string, string], EventId>,
  'addTask' : ActorMethod<[[] | [Timestamp], string, string], TaskId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAllDataForCaller' : ActorMethod<[], undefined>,
  'clearAllDataForUser' : ActorMethod<[Principal], undefined>,
  'deleteEvent' : ActorMethod<[EventId], undefined>,
  'deleteTask' : ActorMethod<[TaskId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEvents' : ActorMethod<[], Array<EncryptedEvent>>,
  'getTasks' : ActorMethod<[], Array<EncryptedTask>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateTaskStatus' : ActorMethod<[TaskId, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];