/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Nat64;
export const EventId = IDL.Nat;
export const TaskId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const EncryptedEvent = IDL.Record({
  'id' : EventId,
  'startTime' : Timestamp,
  'endTime' : Timestamp,
  'encryptedTitle' : IDL.Text,
  'encryptedDescription' : IDL.Text,
});
export const EncryptedTask = IDL.Record({
  'id' : TaskId,
  'isCompleted' : IDL.Bool,
  'deadline' : IDL.Opt(Timestamp),
  'encryptedDetails' : IDL.Text,
  'encryptedTitle' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEvent' : IDL.Func(
      [Timestamp, Timestamp, IDL.Text, IDL.Text],
      [EventId],
      [],
    ),
  'addTask' : IDL.Func([IDL.Opt(Timestamp), IDL.Text, IDL.Text], [TaskId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAllDataForCaller' : IDL.Func([], [], []),
  'clearAllDataForUser' : IDL.Func([IDL.Principal], [], []),
  'deleteEvent' : IDL.Func([EventId], [], []),
  'deleteTask' : IDL.Func([TaskId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEvents' : IDL.Func([], [IDL.Vec(EncryptedEvent)], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(EncryptedTask)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateTaskStatus' : IDL.Func([TaskId, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Nat64;
  const EventId = IDL.Nat;
  const TaskId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const EncryptedEvent = IDL.Record({
    'id' : EventId,
    'startTime' : Timestamp,
    'endTime' : Timestamp,
    'encryptedTitle' : IDL.Text,
    'encryptedDescription' : IDL.Text,
  });
  const EncryptedTask = IDL.Record({
    'id' : TaskId,
    'isCompleted' : IDL.Bool,
    'deadline' : IDL.Opt(Timestamp),
    'encryptedDetails' : IDL.Text,
    'encryptedTitle' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEvent' : IDL.Func(
        [Timestamp, Timestamp, IDL.Text, IDL.Text],
        [EventId],
        [],
      ),
    'addTask' : IDL.Func(
        [IDL.Opt(Timestamp), IDL.Text, IDL.Text],
        [TaskId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAllDataForCaller' : IDL.Func([], [], []),
    'clearAllDataForUser' : IDL.Func([IDL.Principal], [], []),
    'deleteEvent' : IDL.Func([EventId], [], []),
    'deleteTask' : IDL.Func([TaskId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEvents' : IDL.Func([], [IDL.Vec(EncryptedEvent)], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(EncryptedTask)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateTaskStatus' : IDL.Func([TaskId, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };